#!/bin/bash
#Configuration/Variable Storage file
#Iceweasel development, released under GNU General Public License (see readme)
#Use the server configuration script in the main menu to set this file up for your system.



LPATH="/$HOME/server/bin/logs" #Logging Path
APATH="/$HOME/server/bin" #auth path
WPATH="/$HOME/server/bin" #world path
RPATH="/$HOME/server"

WORLD="worldserver" #world binary
AUTH="authserver" #auth binary

CONF="/$HOME/server"
CONFI="/etc"
CONFIGS="$CONF/$confi"

SCREEN_CHK=$(ls /var/run/screen/S-$USER/)
SCREEN_LOC="/var/run/screen/S-$USER/"

AUTH_SCREEN="/var/run/screen/S-$USER/*.auth"
WORLD_SCREEN="/var/run/screen/S-$USER/*.world"
RESTARTER_SCREEN="/var/run/screen/S-$USER/*.restarter"

START_LOG="$LPATH/startup.log"
RESTART_LOG="$LPATH/restart.log"
ACC_LOG="$LPATH/account.log"
PERM_LOG="$LPATH/access.log"
CRASH_LOG="$LPATH/$RIGHT_NOW"

AUTH_LOC="./bin/$AUTH"
WORLD_LOC="./bin/$WORLD"
RESTARTER_LOC="./restarter"

FIRST_START=0
RIGHT_NOW=$(date +"%x %r %Z")
